---
# Firewall configuration using UFW

- name: Install UFW
  ansible.builtin.apt:
    name: ufw
    state: present
  become: yes

- name: Configure UFW default policies
  community.general.ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  loop:
    - { direction: incoming, policy: deny }
    - { direction: outgoing, policy: allow }
  become: yes

- name: Configure UFW rules
  community.general.ufw:
    rule: allow
    port: "{{ item.port | string }}"
    proto: "{{ item.proto }}"
    comment: "{{ item.comment | default('') }}"
  loop: "{{ base_firewall_allowed_ports }}"
  become: yes

- name: Enable UFW
  community.general.ufw:
    state: enabled
  become: yes
