---
# Node Exporter role defaults

# Node Exporter version and configuration
node_exporter_version: 1.6.1
node_exporter_user: node_exporter
node_exporter_group: node_exporter
node_exporter_binary_dir: /usr/local/bin
node_exporter_web_listen_address: "0.0.0.0:9100"
node_exporter_config_dir: /etc/node_exporter
node_exporter_log_dir: /var/log/node_exporter

# Node Exporter collectors to enable
node_exporter_enabled_collectors:
  - systemd
  - textfile:
      directory: "{{ node_exporter_config_dir }}/textfile_collector"
  - filesystem:
      ignored-mount-points: "^/(dev|proc|sys|var/lib/docker/.+)($|/)"
      ignored-fs-types: "^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$"
  - netclass
  - netdev
  - netstat
  - loadavg
  - meminfo
  - diskstats
  - entropy
  - filefd
  - processes
  - interrupts
  - mdadm
  - temperature
  - thermal_zone
  - time
  - timex
  - vmstat
  - xfs
  - zfs

# Node Exporter collectors to disable
node_exporter_disabled_collectors: []

# Custom textfile collector directory
node_exporter_textfile_deploy_dir: "{{ node_exporter_config_dir }}/textfile_collector"

# Firewall ports
node_exporter_firewall_ports:
  - port: 9100
    proto: tcp
    comment: "Node Exporter"