---
# Production Raspberry Pi cluster
all:
  children:
    production:
      hosts:
        pi-a:
          ansible_host: pi-a.local
          ansible_user: william
          pi_serial: "REPLACE_WITH_SERIAL"
        pi-b:
          ansible_host: pi-b.local
          ansible_user: william
          pi_serial: "REPLACE_WITH_SERIAL"
        pi-c:
          ansible_host: pi-c.local
          ansible_user: william
          pi_serial: "REPLACE_WITH_SERIAL"
      vars:
        ansible_python_interpreter: /usr/bin/python3
        environment_name: production
        arch: arm64

    observability:
      hosts:
        pi-a:  # Prometheus, Grafana, Loki
      vars:
        prometheus_port: 9090
        grafana_port: 3000
        loki_port: 3100

    ingress:
      hosts:
        pi-b:  # Caddy/Traefik
      vars:
        ingress_type: caddy

    # Canary group for staged rollouts
    canary:
      hosts:
        pi-a:
