---
# Base role handlers

- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted
  become: yes

- name: Restart chrony
  ansible.builtin.systemd:
    name: chrony
    state: restarted
  become: yes

- name: Restart unattended-upgrades
  ansible.builtin.systemd:
    name: unattended-upgrades
    state: restarted
  become: yes
