---
galaxy_info:
  role_name: podman
  author: william
  description: Podman container runtime configuration for homelab
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - noble
  galaxy_tags:
    - containers
    - podman
    - quadlet
    - systemd

dependencies:
  - base