---
galaxy_info:
  author: homelab
  description: Node Exporter role for Pi cluster
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - focal

dependencies: []