http:
  routers:
    # Homelab subdomain routes
    homelab-main:
      rule: "Host(`homelab.grenlan.com`)"
      service: grafana
      entryPoints:
        - websecure
      tls: {}
    
    grafana-homelab:
      rule: "Host(`grafana.homelab.grenlan.com`)"
      service: grafana
      entryPoints:
        - websecure
      tls: {}
    
    prometheus-homelab:
      rule: "Host(`prometheus.homelab.grenlan.com`)"
      service: prometheus
      entryPoints:
        - websecure
      tls: {}
    
    loki-homelab:
      rule: "Host(`loki.homelab.grenlan.com`)"
      service: loki
      entryPoints:
        - websecure
      tls: {}
    
    # Keep existing routes for backward compatibility
    grafana-legacy:
      rule: "Host(`grafana.grenlan.com`)"
      service: grafana
      entryPoints:
        - websecure
      tls: {}
    
    prometheus-legacy:
      rule: "Host(`prometheus.grenlan.com`)"
      service: prometheus
      entryPoints:
        - websecure
      tls: {}
  
  services:
    grafana:
      loadBalancer:
        servers:
          - url: "http://192.168.1.12:3000"
        healthCheck:
          path: /api/health
          interval: 30s
          timeout: 3s
    
    prometheus:
      loadBalancer:
        servers:
          - url: "http://192.168.1.12:9090"
        healthCheck:
          path: /-/healthy
          interval: 30s
          timeout: 3s
    
    loki:
      loadBalancer:
        servers:
          - url: "http://192.168.1.12:3100"
        healthCheck:
          path: /ready
          interval: 30s
          timeout: 3s
    
    minio:
      loadBalancer:
        servers:
          - url: "http://192.168.1.13:9000"
    
    minio-console:
      loadBalancer:
        servers:
          - url: "http://192.168.1.13:9001"