# Fixed Traefik configuration for v3.1
# Resolves SNI handshake issues

api:
  dashboard: true
  debug: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  
  websecure:
    address: ":443"
    http:
      tls:
        domains:
          - main: "grenlan.com"
            sans:
              - "*.grenlan.com"
              - "*.homelab.grenlan.com"
              - "homelab.grenlan.com"
  
  metrics:
    address: ":8082"

providers:
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addServicesLabels: true

log:
  level: DEBUG  # Temporarily set to DEBUG for troubleshooting
  filePath: /var/log/traefik/traefik.log

accessLog:
  filePath: /var/log/traefik/access.log

ping:
  entryPoint: web

serversTransport:
  insecureSkipVerify: true