---
# Handlers for node-exporter role

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes

- name: restart node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted
  become: yes